In [2]:
from twitterscraper import query_tweets
from twitterscraper.query import query_user_info

import datetime as dt 
import pandas as pd

INFO: {'User-Agent': 'Opera/9.80 (X11; Linux i686; Ubuntu/14.10) Presto/2.12.388 Version/12.16'}

In [3]:
def get_user_info(twitter_user):
    """
    An example of using the query_user_info method
    :param twitter_user: the twitter user to capture user data
    :return: twitter_user_data: returns a dictionary of twitter user data
    """
    user_info = query_user_info(user= twitter_user)
    twitter_user_data = {}

    try:
        twitter_user_data["user"] = user_info.user
    except:
        twitter_user_data["user"] = "Sin user"

    try:
        twitter_user_data["fullname"] = user_info.full_name
    except:
        twitter_user_data["fullname"] = "Sin fullname"

    try:
        twitter_user_data["location"] = user_info.location
    except:
        twitter_user_data["location"] = "Sin locación"

    try:
        twitter_user_data["blog"] = user_info.blog
    except:
        twitter_user_data["blog"] = "Sin blog"

    try:
        twitter_user_data["date_joined"] = user_info.date_joined
    except:
        twitter_user_data["date_joined"] = "Sin fecha de inicio"

    try:
        twitter_user_data["id"] = user_info.id
    except:
        twitter_user_data["id"] = "Sin ID"

    try:
        twitter_user_data["num_tweets"] = user_info.tweets
    except:
        twitter_user_data["num_tweets"] = "Sin tweets rastreables"

    try:
        twitter_user_data["following"] = user_info.following
    except:
        twitter_user_data["following"] = "Sin seguidos"

    try:
        twitter_user_data["followers"] = user_info.followers
    except:
        twitter_user_data["followers"] = "Sin followers"

    try:
        twitter_user_data["likes"] = user_info.likes
    except:
        twitter_user_data["likes"] = "Sin likes"

    try:
        twitter_user_data["lists"] = user_info.lists
    except:
        twitter_user_data["lists"] = "Sin listas"

    return twitter_user_data;

In [4]:
"""
#   Ejemplo de inicialización de requerimiento

#   begin_date =  dt.date(2020,1,1)
#   end_date   =  dt.date(2020,4,1)
#   lann       =  "spanish"
#   tweets     =  query_tweets("tema o keywords", begindate = begin_date, enddate=end_date, lang = lann)
#   dataframe  =  pd.DataFrame(t.__dict__ for t in tweets)

#   Guardar consultas localmente

#   dataframe.to_pickle('123.pkl')               #to save the dataframe, df to 123.pkl
#   readed_pickle = pd.read_pickle('123.pkl')

#   rastrear usuarios
#   users = df["username"].unique()
"""

'\n#   Ejemplo de inicialización de requerimiento\n\n#   begin_date =  dt.date(2020,1,1)\n#   end_date   =  dt.date(2020,4,1)\n#   lann       =  "spanish"\n#   tweets     =  query_tweets("tema o keywords", begindate = begin_date, enddate=end_date, lang = lann)\n#   dataframe  =  pd.DataFrame(t.__dict__ for t in tweets)\n\n#   Guardar consultas localmente\n\n#   dataframe.to_pickle(\'123.pkl\')               #to save the dataframe, df to 123.pkl\n#   readed_pickle = pd.read_pickle(\'123.pkl\')\n\n#   rastrear usuarios\n#   users = df["username"].unique()\n'

In [26]:
begin_date =  dt.date(2019,9,1)
end_date   =  dt.date(2020,4,1)
lann       =  "spanish"
tweets     =  query_tweets("cdmx", begindate = begin_date, enddate=end_date, lang = lann)
dataframe  =  pd.DataFrame(t.__dict__ for t in tweets)

INFO: queries: ['cdmx since:2019-09-01 until:2019-09-11', 'cdmx since:2019-09-11 until:2019-09-22', 'cdmx since:2019-09-22 until:2019-10-02', 'cdmx since:2019-10-02 until:2019-10-13', 'cdmx since:2019-10-13 until:2019-10-24', 'cdmx since:2019-10-24 until:2019-11-03', 'cdmx since:2019-11-03 until:2019-11-14', 'cdmx since:2019-11-14 until:2019-11-25', 'cdmx since:2019-11-25 until:2019-12-05', 'cdmx since:2019-12-05 until:2019-12-16', 'cdmx since:2019-12-16 until:2019-12-27', 'cdmx since:2019-12-27 until:2020-01-06', 'cdmx since:2020-01-06 until:2020-01-17', 'cdmx since:2020-01-17 until:2020-01-28', 'cdmx since:2020-01-28 until:2020-02-07', 'cdmx since:2020-02-07 until:2020-02-18', 'cdmx since:2020-02-18 until:2020-02-29', 'cdmx since:2020-02-29 until:2020-03-10', 'cdmx since:2020-03-10 until:2020-03-21', 'cdmx since:2020-03-21 until:2020-04-01']
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets (0 new).
INFO: Got 783 tweets (783 new).
INFO: Got 1556 tweets (773 new).
INFO: Got 2369 tweets (813 new).
INFO: Got 3113 tweets (744 new).
INFO: Got 3877 tweets (764 new).
INFO: Got 4661 tweets (784 new).
INFO: Got 5454 tweets (793 new).
INFO: Got 6215 tweets (761 new).
INFO: Got 6990 tweets (775 new).
INFO: Got 7732 tweets (742 new).
INFO: Got 8521 tweets (789 new).
INFO: Got 9279 tweets (758 new).
INFO: Got 10061 tweets (782 new).
INFO: Got 10828 tweets (767 new).
INFO: Got 11606 tweets (778 new).
INFO: Got 12311 tweets (705 new).
INFO: Got 13078 tweets (767 new).
INFO: Got 13899 tweets (821 new).

In [27]:
dataframe.head()

,screen_name,username,user_id,tweet_id,tweet_url,timestamp,timestamp_epochs,text,text_html,links,...,has_media,img_urls,video_url,likes,retweets,replies,is_replied,is_reply_to,parent_tweet_id,reply_to_users
0,diegoypato,Diego,737646519801634816,1175560323786391552,/diegoypato/status/1175560323786391552,2019-09-21 23:59:56,1569110396,@Claudiashein @PGJDF_CDMX @CiroGomezL @Mendivi...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,True,[https://pbs.twimg.com/media/EFBt3BHU8AAI8rD.jpg],,0,2,0,False,False,,[]
1,cybersaori,iselita,2864988226,1175560312495497216,/cybersaori/status/1175560312495497216,2019-09-21 23:59:54,1569110394,— asistiendo a EXA Concierto 2019 CDMX en For...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[https://www.facebook.com/100010135420876/post...,...,False,[],,0,0,0,False,False,,[]
2,OR_2,OR²,95502376,1175560297408544768,/OR_2/status/1175560297408544768,2019-09-21 23:59:50,1569110390,"3 razones para visitar CDMX, Capital Cultural ...","<p class=""TweetTextSize js-tweet-text tweet-te...",[https://www.mexicodesconocido.com.mx/razones-...,...,False,[],,0,0,0,False,False,,[]
3,naranjadcorazon,NaranjadeCorazon,499917856,1175560276969574400,/naranjadcorazon/status/1175560276969574400,2019-09-21 23:59:45,1569110385,Cuánto costará la indemnización de @Carlos8Rei...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,17,9,3,True,False,,[]
4,Fruttaffy,Fatima,174503812,1175560263829000202,/Fruttaffy/status/1175560263829000202,2019-09-21 23:59:42,1569110382,En la nota escribieron que la Universidad Pana...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,0,0,0,False,True,1175557066905153536,"[{'screen_name': 'lajornadaonline', 'user_id':..."